theme = "slick"
icons = "awesome"

[[block]]                                                                       
block = "music"                                                                 
player = "spotify"                                                              
buttons = ["play", "next"] 

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
upower = true
format = "{percentage}% {time} {power}W"

[[block]]
block = "time"
format = "%a %m%d  %T %Z"
timezone = "US/Pacific"
interval = 60
